<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPKHsL7F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPKHsL7F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPKHsL7F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPKHsL7F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPKHsL7F\App_KernelDevDebugContainer([
    'container.build_hash' => 'PKHsL7F',
    'container.build_id' => 'b66bb13e',
    'container.build_time' => 1770550282,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPKHsL7F');
