<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZBQ8Qy4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZBQ8Qy4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZBQ8Qy4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZBQ8Qy4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZBQ8Qy4\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZBQ8Qy4',
    'container.build_id' => '3c9a3fe4',
    'container.build_time' => 1770884002,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZBQ8Qy4');
