<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGmbm4bL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGmbm4bL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGmbm4bL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGmbm4bL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGmbm4bL\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gmbm4bL',
    'container.build_id' => 'b62e4f29',
    'container.build_time' => 1770883916,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGmbm4bL');
