<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJOZAiWu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJOZAiWu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJOZAiWu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJOZAiWu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJOZAiWu\App_KernelDevDebugContainer([
    'container.build_hash' => 'JOZAiWu',
    'container.build_id' => '7609aa65',
    'container.build_time' => 1770501184,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJOZAiWu');
