<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'homepage' => [['article'], ['article' => 'main', '_controller' => 'App\\e01Bundle\\Controller\\DefaultController::showPage'], [], [['variable', '/', '[^/]++', 'article', true], ['text', '/e01']], [], [], []],
    'App\e01Bundle\Controller\DefaultController::showPage' => [['article'], ['article' => 'main', '_controller' => 'App\\e01Bundle\\Controller\\DefaultController::showPage'], [], [['variable', '/', '[^/]++', 'article', true], ['text', '/e01']], [], [], []],
];
