<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'e02_index' => [[], ['_controller' => 'App\\e02Bundle\\Controller\\DefaultController::indexAction'], [], [['text', '/e02']], [], [], []],
    'App\e02Bundle\Controller\DefaultController::indexAction' => [[], ['_controller' => 'App\\e02Bundle\\Controller\\DefaultController::indexAction'], [], [['text', '/e02']], [], [], []],
];
