<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRkpsFmo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRkpsFmo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRkpsFmo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRkpsFmo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRkpsFmo\App_KernelDevDebugContainer([
    'container.build_hash' => 'RkpsFmo',
    'container.build_id' => '9e1543a4',
    'container.build_time' => 1770883758,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRkpsFmo');
