<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260209213758 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create orm_data table and ensure sql_data exists';
    }

    public function up(Schema $schema): void
    {
        // Créer la table orm_data
        $this->addSql('CREATE TABLE orm_data (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            content VARCHAR(255) NOT NULL, 
            imported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
            PRIMARY KEY(id)
        )');
        
        // Créer sql_data seulement si elle n'existe pas déjà
        $this->addSql('CREATE TABLE IF NOT EXISTS sql_data (
            id SERIAL PRIMARY KEY,
            raw_content VARCHAR(255) NOT NULL
        )');
    }

    public function down(Schema $schema): void
    {
        // Supprimer orm_data
        $this->addSql('DROP TABLE orm_data');
        
        // On garde sql_data (pas de DROP)
    }
}