<?php

namespace ContainerJOZAiWu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G7Cf1geService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G7Cf1ge' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G7Cf1ge'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'request' => ['privates', '.errored.cZMKsay', NULL, 'Cannot determine controller argument for "App\\e02Bundle\\Controller\\DefaultController::indexAction()": the $request argument is type-hinted with the non-existent class or interface: "App\\e02Bundle\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'request' => '?',
        ]);
    }
}
