<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260212140957 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE sql_data_id_seq CASCADE');
        $this->addSql('CREATE TABLE ex12_persons (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, enable BOOLEAN NOT NULL, birthdate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, address_id INT DEFAULT NULL, bank_account_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BB059654F85E0677 ON ex12_persons (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BB0596545E237E06 ON ex12_persons (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BB059654E7927C74 ON ex12_persons (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BB059654F5B7AF75 ON ex12_persons (address_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BB05965412CB990C ON ex12_persons (bank_account_id)');
        $this->addSql('ALTER TABLE ex12_persons ADD CONSTRAINT FK_BB059654F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ex12_persons ADD CONSTRAINT FK_BB05965412CB990C FOREIGN KEY (bank_account_id) REFERENCES bank_account (id) NOT DEFERRABLE');
        $this->addSql('DROP TABLE orm_data');
        $this->addSql('DROP TABLE persons CASCADE');
        $this->addSql('DROP TABLE sql_data');
        $this->addSql('DROP INDEX idx_d4e6f81217bbb47');
        $this->addSql('ALTER TABLE address DROP person_id');
        $this->addSql('DROP INDEX idx_53a23e0a217bbb47');
        $this->addSql('ALTER TABLE bank_account DROP person_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE sql_data_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE orm_data (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content VARCHAR(255) NOT NULL, imported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE persons (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, enable BOOLEAN NOT NULL, birthdate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_a25cc7d3f85e0677 ON persons (username)');
        $this->addSql('CREATE UNIQUE INDEX uniq_a25cc7d3e7927c74 ON persons (email)');
        $this->addSql('CREATE UNIQUE INDEX uniq_a25cc7d35e237e06 ON persons (name)');
        $this->addSql('CREATE TABLE sql_data (id INT DEFAULT nextval(\'sql_data_id_seq\'::regclass) NOT NULL, raw_content TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE ex12_persons DROP CONSTRAINT FK_BB059654F5B7AF75');
        $this->addSql('ALTER TABLE ex12_persons DROP CONSTRAINT FK_BB05965412CB990C');
        $this->addSql('DROP TABLE ex12_persons');
        $this->addSql('ALTER TABLE address ADD person_id INT NOT NULL');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT fk_d4e6f81217bbb47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_d4e6f81217bbb47 ON address (person_id)');
        $this->addSql('ALTER TABLE bank_account ADD person_id INT NOT NULL');
        $this->addSql('ALTER TABLE bank_account ADD CONSTRAINT fk_53a23e0a217bbb47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_53a23e0a217bbb47 ON bank_account (person_id)');
    }
}
