<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260212134324 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE address (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, street VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, zipcode VARCHAR(255) NOT NULL, person_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D4E6F81217BBB47 ON address (person_id)');
        $this->addSql('CREATE TABLE bank_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bank_name VARCHAR(255) NOT NULL, iban VARCHAR(255) NOT NULL, person_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_53A23E0A217BBB47 ON bank_account (person_id)');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F81217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bank_account ADD CONSTRAINT FK_53A23E0A217BBB47 FOREIGN KEY (person_id) REFERENCES persons (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE persons ADD phone VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE persons DROP address');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A25CC7D35E237E06 ON persons (name)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE address DROP CONSTRAINT FK_D4E6F81217BBB47');
        $this->addSql('ALTER TABLE bank_account DROP CONSTRAINT FK_53A23E0A217BBB47');
        $this->addSql('DROP TABLE address');
        $this->addSql('DROP TABLE bank_account');
        $this->addSql('DROP INDEX UNIQ_A25CC7D35E237E06');
        $this->addSql('ALTER TABLE persons ADD address TEXT NOT NULL');
        $this->addSql('ALTER TABLE persons DROP phone');
    }
}
