<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260214162314 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value INT NOT NULL, voter_id INT NOT NULL, post_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5F3EA0C4EBB4B8AD ON app_vote (voter_id)');
        $this->addSql('CREATE INDEX IDX_5F3EA0C44B89032C ON app_vote (post_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_vote_user_post ON app_vote (voter_id, post_id)');
        $this->addSql('ALTER TABLE app_vote ADD CONSTRAINT FK_5F3EA0C4EBB4B8AD FOREIGN KEY (voter_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_vote ADD CONSTRAINT FK_5F3EA0C44B89032C FOREIGN KEY (post_id) REFERENCES app_post (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_user ADD reputation INT DEFAULT 0 NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE app_vote DROP CONSTRAINT FK_5F3EA0C4EBB4B8AD');
        $this->addSql('ALTER TABLE app_vote DROP CONSTRAINT FK_5F3EA0C44B89032C');
        $this->addSql('DROP TABLE app_vote');
        $this->addSql('ALTER TABLE app_user DROP reputation');
    }
}
